export let REDUCER_ROUTERS = {
    AUTH: {
        CREATE_USER_REQUEST: "CREATE_USER_REQUEST",
        CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
        CREATE_USER_FAILURE: "CREATE_USER_FAILURE",

        LOGIN_USER_REQUEST: "LOGIN_USER_REQUEST",
        LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
        LOGIN_USER_FAILURE: "LOGIN_USER_FAILURE",

        LOGOUT_USER_REQUEST: "LOGOUT_USER_REQUEST",
        LOGOUT_USER_SUCCESS: "LOGOUT_USER_SUCCESS",
        LOGOUT_USER_FAILURE: "LOGOUT_USER_FAILURE",
    },
    EVENTS: {
        // low priority
    },
    SCHEDULE: {
        GET_SCHEDULE_REQUEST: "GET_SCHEDULE_REQUEST",
        GET_SCHEDULE_SUCCESS: "GET_SCHEDULE_SUCCESS",
        GET_SCHEDULE_FAILURE: "GET_SCHEDULE_FAILURE",
    },
    SPONSORS: {
        REGISTER_SPONSOR_FOR_EVENT_REQUEST: "REGISTER_SPONSOR_FOR_EVENT_REQUEST",
        REGISTER_SPONSOR_FOR_EVENT_SUCCESS: "REGISTER_SPONSOR_FOR_EVENT_SUCCESS",
        REGISTER_SPONSOR_FOR_EVENT_FAILURE: "REGISTER_SPONSOR_FOR_EVENT_FAILURE",

        GET_SPONSORS_REQUEST: "GET_SPONSORS_REQUEST",
        GET_SPONSORS_SUCCESS: "GET_SPONSORS_SUCCESS",
        GET_SPONSORS_FAILURE: "GET_SPONSORS_FAILURE",
    },
    USER: {
        UPDATE_USER_REQUEST: "UPDATE_USER_REQUEST",
        UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
        UPDATE_USER_FAILURE: "UPDATE_USER_FAILURE",

        GET_USER_REQUEST: "GET_USER_REQUEST",
        GET_USER_SUCCESS: "GET_USER_SUCCESS",
        GET_USER_FAILURE: "GET_USER_FAILURE",
    }
}