# Generated by Django 2.1.1 on 2018-09-26 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betaapplications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hackedbetaapplication',
            old_name='graduationYear',
            new_name='graduation_year',
        ),
    ]
